// Generated by CoffeeScript 1.3.3

(function($) {
  var getNewLayerOpacity, getNumberData, initializeFadableLayers;
  $(function() {
    var layers, updateFadableLayers;
    layers = initializeFadableLayers();
    updateFadableLayers = function(e) {
      var layer, scrollTop, _i, _len;
      scrollTop = parseInt($(document).scrollTop());
      for (_i = 0, _len = layers.length; _i < _len; _i++) {
        layer = layers[_i];
        layer.$elem.css('opacity', getNewLayerOpacity(layer, scrollTop));
      }
      return true;
    };
    updateFadableLayers();
    return $(document).scroll(updateFadableLayers);
  });
  initializeFadableLayers = function() {
    var $layer, $layers, data, layer, layers, _i, _len;
    layers = [];
    $layers = $(".fadable");
    if ($layers != null) {
      for (_i = 0, _len = $layers.length; _i < _len; _i++) {
        layer = $layers[_i];
        data = {};
        $layer = $(layer);
        data.$elem = $layer;
        data.type = $layer.data('fadable-type') || 'out';
        data.start = getNumberData($layer.data('fadable-start')) || 0;
        data.end = getNumberData($layer.data('fadable-end')) || $(document).height();
        switch (data.type) {
          case 'out':
            data.init = getNumberData(data.$elem.css('opacity')) || 1;
            data.range = data.init / (data.end - data.start);
            break;
          case 'in':
            data.init = getNumberData(data.$elem.css('opacity')) || 0;
            data.range = (1 - data.init) / (data.end - data.start);
        }
        layers.push(data);
      }
    }
    return layers;
  };
  getNewLayerOpacity = function(layer, scrollTop) {
    var diff, opacity;
    diff = scrollTop - layer.start;
    opacity = 0;
    switch (layer.type) {
      case 'out':
        opacity = layer.init - layer.range * diff;
        if (opacity < 0) {
          opacity = 0;
        }
        if (opacity > layer.init) {
          opacity = layer.init;
        }
        break;
      case 'in':
        opacity = layer.init + layer.range * diff;
        if (opacity > 1) {
          opacity = 1;
        }
        if (opacity < layer.init) {
          opacity = layer.init;
        }
    }
    return opacity;
  };
  return getNumberData = function(numStr) {
    if (numStr != null) {
      return parseInt(numStr);
    } else {
      return null;
    }
  };
})(window.jQuery);
